### ISSUE TITLE
Using with alternative rate stores

### ISSUE THREAD

**Issue by RKushnir** [RubyMoney/eu_central_bank#61]
Hello,
The `money` gem allows you to use custom stores(ActiveRecord, Redis etc) in place of the default memory store. The way `EuCentralBankHistoricalDataSupport` module is implemented in this gem seems to be tied to that memory store.
Do you have an idea how I can go about replacing it with a Redis store? I suspect, it's only possible by rewriting the mentioned module to handle it in a more abstract way, right? Thanks.

**Comment by antstorm** [comment]
@RKushnir unfortunately it looks like it is tied to that memory store. I think the only reason for it is the fact that default `MemoryStore` and it's interface don't support storing rates for a specific date, which this gem relies on.

It sounds like `money` gem could really benefit from this change.

**Comment by RKushnir** [comment]
@antstorm Sounds good. I figured someone already suggested that a while ago https://github.com/RubyMoney/money/issues/300 , but it didn't receive support.
The mentioned https://github.com/atwam/money-historical-bank doesn't seem to be the right concept, as "historicality" shouldn't tie you to a specific bank.
So I don't know how to solve this.

**Comment by antstorm** [comment]
@RKushnir while it definitely shouldn't be the default behaviour I don't see a reason why there shouldn't be an easy way of implementing it. Maybe we should have 2 base classes for RateStores with and without date support, allowing other devs to extend the right one when implementing their own RateStores.

Otherwise it encourages monkey-patching (this gem is a good example) and that's something we certainly want to avoid.
